version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    command: sh -c "xvfb-run -a uvicorn app.api.endpoints.main:app --host 0.0.0.0 --port 8000"
